You are now the proud owner of:

http://{{host}}/posts/{{address}}/{{ post_name }}.html

Your first post titled "{{ original['Subject'] }}" is already posted and
you can continue to post by sending email to:

{{ post_name }}@{{ host }}

If you would like to delete the post you just made, simply send an email
to:

{{ post_name }}-delete@{{host}}

It will be removed shortly after that, but not immediately.  We'll
notify you when it is finally removed.

You can get more information on things you can do with the Salmon project
OSB at:

http://{{host}}/help.html

Thanks!

---
EmailToBlog
http://{{host}}/
A Salmon project example
